baseURL = "https://karanbirsingh7.github.io/"
title = "karanbir"
theme = "hugo-coder"
languageCode = "en"
enableEmoji = true
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	author = "Karanbir Singh"
	info = "SW/SRE"
	description = "[ Automation | Cloud | Containers ]"
	keywords = "blog, developer, personal, sre"
	avatarurl = "img/avatar.png"
	homepage = false
	enableTwemoji = true
	colorScheme = "auto"
	hidecolorschemetoggle = false

	# Add pagetitle to homepage <title> tag
	#pagetitle = "karanbirsingh7"

	# Add a subtitle to your website
	subtitle = "Senior Cloud Engineer @ RBC | Working with Cloud & Containers"

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Add list of sections that should show up on the homepage
    mainSections = ["posts"]


# Navigation

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2


# Social Menu
	[[params.social]]
	name = "Github"
	icon = "fa fa-github fa-2x"
	weight = 3
	url = "https://github.com/karanbirsingh7"

[[params.social]]
	name = "Email"
	icon = "fa fa-envelope fa-2x"
	weight = 3
	url = "mailto:karanbirsingh1161@gmail.com"

#[[params.social]]
#	name = "Twitter"
#	icon = "fa fa-twitter fa-2x"
#	weight = 3
#	url = "https://twitter.com/karanb1r_singh/"